HathorNetwork/hathor-wallet

src/App.js
src/api/axiosInstance.js
src/api/wallet.js
src/components/RequestError.js
src/constants.js
src/reducers/index.js
src/screens/LoadingAddresses.js

- Adding timeout to requests;
- Aligning in the center the loading addresses screen;
- If an error happens while loading addresses, the user now can change the server without waiting finish loading (that would never finish).

Fix minor bugs in the wallet

---

src/App.js
src/utils/wallet.js

Also blocks notifications are different now

fix: dont show notification for txs generated from same wallet anymore

---

src/actions/index.js
src/api/axiosInstance.js
src/components/RequestError.js
src/reducers/index.js

feat: adapting the error message when request fails because of a 503

---

src/actions/index.js
src/api/axiosInstance.js
src/components/RequestError.js
src/reducers/index.js

feat: adding a link to show advanced request error detail

---

src/components/Transactions.js
src/components/tokens/TokenAction.js
src/index.scss
src/screens/CreateToken.js
src/screens/LoadingAddresses.js
src/screens/SendTokens.js
src/screens/Server.js
src/screens/TransactionDetail.js

Closes https://github.com/HathorNetwork/hathor-wallet/issues/66

style: setting loading color as purple hathor

---

package-lock.json
package.json
src/components/ModalAddManyTokens.js
src/screens/CreateToken.js

Closes https://github.com/HathorNetwork/hathor-wallet/issues/62
Closes https://github.com/HathorNetwork/hathor-wallet/issues/69

Adding emoji to register many tokens regex

---

src/components/TxTextInput.js
src/screens/DashboardTx.js
src/utils/i18n.js

fix(i18n): Missing key props in some places

---

src/App.js
src/storage.js

fix: crash while loading

---

src/index.scss

fix: menu mobile is not transparent anymore

---

src/components/OutputsWrapper.js
src/index.scss

Old screen:
New screen:
With timelock:
Close #76

style: increase address input field width

---

package-lock.json
package.json
src/App.js
src/utils/tokens.js

refactor: small changes to support new lib version

---

src/components/RequestError.js
src/index.scss

fix: reload for address history request error and customizing message

---

src/screens/LoadWallet.js

Enumerate words written while importing a wallet

---

src/components/InputNumber.js
src/components/OutputsWrapper.js
src/components/SendTokensOne.js
src/components/tokens/TokenMelt.js
src/components/tokens/TokenMint.js
src/screens/CreateToken.js

- New component <InputNumber /> to enhance the experience of typing numbers
- Use InputNumber on CreateToken, TokenMint, TokenMelt and SendTokens

feat: thousand separator on value input

---

locale/texts.pot
src/components/ModalBackupWords.js
src/constants.js
src/index.scss
src/screens/NewWallet.js
src/screens/Wallet.js
src/screens/WalletVersionError.js

- Validates the backup in five steps using words randomly chosen between the 24 seed words to assure that the backup was correctly done.
- In each step, the user must find the correct word between some wrong words, similar to the mobile wallet backup.

feat: New backup validation

---

locale/texts.pot
package-lock.json
package.json
public/electron.js
src/App.js
src/components/ModalAlert.js
src/components/Navigation.js
src/constants.js
src/screens/AddressList.js
src/screens/LockedWallet.js
src/screens/Server.js
src/screens/TransactionDetail.js
src/utils/helpers.js
src/utils/version.js

Still need to bump the lib version, so the tx mining service works for the testnet

feat: updating lib network when changing for a testnet/mainnet server

---

QA.md

Chore: update ledger qa steps

---

locale/texts.pot
src/constants.js
src/screens/WalletType.js

feat: explain about developer mode and add link to ledger guide on medium

---

locale/texts.pot
package-lock.json
package.json
src/App.js
src/actions/index.js
src/components/InputNumber.js
src/components/NFTListElement.js
src/components/Navigation.js
src/components/OutputsWrapper.js
src/components/SendTokensOne.js
src/components/TokenAdministrative.js
src/components/TokenBar.js
src/components/TokenGeneralInfo.js
src/components/TokenHistory.js
src/components/TxData.js
src/components/WalletBalance.js
src/components/tokens/TokenAction.js
src/components/tokens/TokenMelt.js
src/components/tokens/TokenMint.js
src/constants.js
src/index.scss
src/reducers/index.js
src/screens/CreateNFT.js
src/screens/NFTList.js
src/screens/SendTokens.js
src/screens/UnknownTokens.js
src/utils/helpers.js
src/utils/tokens.js
src/utils/wallet.js

Different from the explorer PR, here I am not writing 'Loading' when I need to show an amount until the metadata is loaded. The main reason for that is because the explorer needs to request the token metadata every time it opens a screen that has a token, then the screen would always 'blink'. 
In the wallet, this is different. I load the metadata of all tokens that belong to the wallet and then I can show the information every time without 'blinking' the screen. There might be a moment on the wallet start after loading the transactions and before loading all metadatas but we always start showing HTR token, then it's unlikely to happen and, if happens, won't be much a problem.
One possible problem that could happen is sending a transaction before loading all metadata because we change the …

feat: customize wallet information if token is an NFT

---

public/contextMenu.js
public/electron.js

- Shows a context menu on mouse right click on all text input fields allowing copy and paste
- Does not allow copy on password fields
- Resolves #211 
https://user-images.githubusercontent.com/3298774/150235177-42f953f5-4b95-41d1-97fc-3f590820a36f.mov

feat: add context menu to copy/paste using only the mouse

---

public/electron.js
public/ledger.js
src/constants.js
src/utils/ledger.js
src/utils/tokens.js

- Implement command methods for new ledger commands

feat: new command handlers

---

public/electron.js
public/ledger.js
src/App.js
src/utils/ledger.js
src/utils/wallet.js

- Verify token signatures on startup

feat(ledger): check token signatures on startup

---

src/components/LedgerSignTokenInfo.js
src/components/ModalLedgerSignToken.js
src/screens/Wallet.js
src/utils/tokens.js

- Create a functional modal to sign token information and save the signature

feat(ledger): sign custom token modal

---

package-lock.json
package.json
public/electron.js
src/constants.js

- Update the wallet desktop version

chore: bump wallet to v0.21.2

---

package-lock.json
package.json
src/actions/index.js
src/reducers/index.js
src/utils/wallet.js

v0.30.0 included some breaking changes, this PR aims to fix these changes so we can update the wallet-lib version safely.
- getTxBalance as async on reducers

chore: update old wallet facade

---

locale/texts.pot
package-lock.json
package.json
public/contextMenu.js
public/electron.js
src/App.js
src/actions/index.js
src/components/ModalResetAllData.js
src/components/NFTListElement.js
src/components/TxData.js
src/constants.js
src/reducers/index.js
src/utils/wallet.js

Release v0.21.2

---

src/screens/WalletType.js
src/utils/wallet.js

During hardware wallet startup we should check all token signatures to make sure they're valid.
The util used to start hardware wallet (and where we were checking the signatures) is not being used so we have to move this to the actual place where we start the hardware wallet and remove the unused util.

feat: check signatures on startup

---

QA.md
package-lock.json
package.json
public/contextMenu.js
public/electron.js
src/App.js
src/components/TxData.js
src/constants.js

Update QA with new interactions for custom tokens on hardware wallet with Ledger.

chore: qa for Ledger custom tokens

---

src/components/SendTokensOne.js
src/screens/SendTokens.js
src/screens/Settings.js
src/screens/Wallet.js
src/screens/WalletType.js
src/utils/version.js

- disable ledger specific features when using software wallet

fix: ledger custom token features showing on software wallet

---

QA.md
package-lock.json
package.json
public/electron.js
public/ledger.js
src/App.js
src/components/LedgerSignTokenInfo.js
src/components/ModalLedgerResetTokenSignatures.js
src/components/ModalLedgerSignToken.js
src/components/SendTokensOne.js
src/constants.js
src/screens/SendTokens.js
src/screens/Settings.js
src/screens/Wallet.js
src/screens/WalletType.js
src/utils/helpers.js
src/utils/ledger.js
src/utils/tokens.js
src/utils/version.js
src/utils/wallet.js

This PR is a conjunction o smaller approved changes to add support for custom tokens on hardware wallets with Ledger (starting at Ledger app version v1.0.2).

feat: ledger custom tokens

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump version v0.22.0

---

QA.md

- Update NFT creation process on QA document

chore: update NFT part on QA document

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump version to v0.22.1

---

QA.md
package-lock.json
package.json
public/electron.js
src/constants.js

Release v0.22.1

---

locale/texts.pot
package-lock.json
package.json
src/App.js
src/constants.js
src/index.scss
src/reducers/index.js
src/screens/Server.js
src/screens/Settings.js
src/utils/version.js
src/utils/wallet.js

https://user-images.githubusercontent.com/3586068/167901342-78e8ca9b-9c62-4ee4-9e3d-32cc4d27dc3f.mov
- The user should be able to change the wallet service base url and websocket url
- The wallet should get the network from storage instead of getting it from the connected fullnode as we should not request the fullnode directly when using the wallet-service facade

feat: wallet service change server

---

src/screens/Server.js

- We should be able to properly change server while on the old facade

fix: issues preventing QA from passing on the current dev branch

---

locale/texts.pot
src/components/ModalAddManyTokens.js
src/components/ModalAddToken.js
src/components/TokenBar.js
src/components/TokenGeneralInfo.js
src/index.scss
src/screens/CustomTokens.js
src/screens/UnknownTokens.js
src/screens/Wallet.js
src/utils/wallet.js

This PR implements one of the features requested by the PR:
- #309
It allows the user to select tokens that will always be shown, despite having zero-balance and the setting "hide zero balance tokens" being turned on.
When registering tokens, the application now checks for its balance and, in case the token would be immediately hidden by the "hide-zero balance tokens" settings, asks the user if this token should always be shown.
- Tokens set to "Always Show" are displayed even if they have zero balance and the "Hide zero balance tokens" setting is active.
- User can set a token to always be shown via its `Token Info` > `About` tab
- User should be asked if the token being registered should always be shown, in case it would be hidden immediately
- User should be asked if the multiple …

feat: always show tokens

---

QA.md

- There should be new steps for testing the "Hide zero-balance tokens" on the QA document

Docs/Update QA for "hide zero balance tokens" feature

---

locale/texts.pot
src/components/InputNumber.js
src/components/ModalAddManyTokens.js
src/components/ModalAddToken.js
src/components/TokenGeneralInfo.js
src/utils/wallet.js

- Fix a bug in which the "Hide zero-balance tokens" was active on the app's first run ( empty _LocalStorage_ )
- Change the word "overwrite" to "override" on the "Hide zero-balance tokens" tooltips

fix: hide feature should be off by default

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump version to v0.23.1

---

locale/texts.pot
package-lock.json
package.json
public/electron.js
src/components/InputNumber.js
src/components/ModalAddManyTokens.js
src/components/ModalAddToken.js
src/components/TokenGeneralInfo.js
src/constants.js
src/utils/wallet.js

Release v0.23.1

---

src/App.js
src/actions/index.js
src/components/ModalAddToken.js
src/components/ModalUnregisteredTokenInfo.js
src/components/TokenGeneralInfo.js
src/reducers/index.js
src/screens/LoadingAddresses.js
src/screens/Wallet.js
src/utils/wallet.js

- A list of bug fixes and small UI/UX improvements listed below.
1. Don't show the option to "Always show token" inside Transaction Detail > Register token modal because it will open modal over modal (see video below).
https://github.com/HathorNetwork/hathor-wallet/commit/c68671526931aa59942134af8ed526feb7bf19b6
2. Click on label works for checkbox click as well in the AddToken modal for Always Show Token.
https://github.com/HathorNetwork/hathor-wallet/commit/694adef08640070830b1be18c5864bfc0c5a7b51
3. If you mark to hide zero balance tokens and the token currently selected has zero balance, then you must select HTR.
https://github.com/HathorNetwork/hathor-wallet/commit/4cdb89cf517acdf6ad7fe5237a1d3e6a1e3ab34a
4. The first time you open the app and load a wallet, the progress goes to 0 …

feat: UI/UX improvements and small fixes

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump to v0.23.2

---

package-lock.json
package.json

chore: bump hathor wallet lib to v0.40.1

---

RELEASING.md
package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump to v0.24.0

---

public/ledger.js

- queue executions should manage transport open/close to avoid sync issues.

fix: ledger queue

---

.gitignore
ELECTRON.md
README.md
package.json

- Remove outdated information and instruction
- Update initialization instruction with electron
- Add guidance to WSL users

docs: improve introduction readings

---

package-lock.json
package.json
src/actions/index.js
src/components/RequestError.js
src/sagas/wallet.js
src/screens/StartHardwareWallet.js
src/screens/UnknownTokens.js

- Fixes an issue on the UnknownTokens page where the tokens would load history indefinetely (1c3e3c118526258b6270584a20bb74c897c0b962)
- Fixes an issue on the hideZeroBalances feature that wouldn't display any tokens because we didn't load their balances (2a90bb694b5591313ac64959e2892b0d395a295b)
- Fixes an issue where the wallet would get stuck on the loading screen after the connection was down and up again (c9499b158971c6221477f9a15ddd2bd92b9887fd and c4f06a8d0b30ab67802adab06112e05773609039)
- Fixes `startWallet` while on Ledger (497dd83da24c949d8b6fe64ce3a2a841a3dbc9b7)

fix: upgrade wallet lib and other fixes

---

QA.md
package-lock.json
package.json
src/components/TxData.js

Depends on https://github.com/HathorNetwork/hathor-wallet-lib/pull/429 and https://github.com/HathorNetwork/hathor-wallet-service/pull/305
- We should use the new facade method `checkAddressesMIne` to decide whether to display the wallet address badge on TxData screen

feat: check addresses mine

---

src/sagas/wallet.js

- Token metadata should download without blocking the `loadTokens` generator

refactor: non blocking load tokens

---

src/components/TokenBar.js
src/index.js
src/screens/UnknownTokens.js
src/screens/Wallet.js

- We should refactor the TokenBar component to be a Function component
- We should refactor the TokenBar to be global and render only on specific routes

refactor: global token bar

---

locale/texts.pot
src/constants.js
src/screens/Settings.js
src/screens/Welcome.js

- Add links for Terms of Service and Privacy Policy in the Welcome and Settings screens

feat: add links for terms of service and privacy policy in the Welcome and Settings screens

---

locale/texts.pot
package-lock.json
package.json
src/actions/index.js
src/api/axiosInstance.js
src/components/TxData.js
src/sagas/wallet.js
src/screens/CreateNFT.js
src/screens/CreateToken.js
src/screens/SendTokens.js
src/screens/Server.js
src/screens/TransactionDetail.js
src/screens/Wallet.js
src/utils/wallet.js

* The wallet-desktop was requesting the full node for the transaction details and it's always requesting the `mainnet` fullnode
* It was rolling back the server and not calling `changeWsServer` on `confirmTestnet`
Here is a video of the retry mechanism for the graphviz queries in the `TxData` screen:
https://user-images.githubusercontent.com/3586068/212172920-3881644b-dab7-4b18-b842-4a43c9bfb705.mov
Here is a video of the retry mechanism for the transaction query:
https://user-images.githubusercontent.com/3586068/212348289-b1c5e80e-9536-4d20-91a6-4fa61f5ae775.mov
Here is a video of the retry mechanism in the transaction weight query:
https://user-images.githubusercontent.com/3586068/212718491-c09c5433-3c07-4288-bec4-20054007cf79.mov

fix: issues found during the QA on 05/01/2023

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump to v0.25.0

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump to  v0.25.1

---

ELECTRON.md
package-lock.json
package.json
public/electron.js
release.sh
scripts/win-ev-sign.js
src/constants.js
src/sagas/wallet.js

Release v0.25.1

---

.github/workflows/e2e.yml

- Cypress workflow actions are updated
- Fixed cypress execution on NodeJS 14

chore: upgrades cypress github-actions

---

.github/workflows/e2e.yml
src/__tests__/components/ModalSendTx.test.js
src/components/ModalAddToken.js
src/components/ModalSendTx.js
src/screens/SentryPermission.js
src/screens/Server.js

This PR fixes the minor bugs found during QA
- A failed validation is trying to hide the modal before it's shown ( [6dca6c5](https://github.com/HathorNetwork/hathor-wallet/pull/395/commits/6dca6c5b44a93a24182caa5147e9fb2c1eaf690e) )
- "Add token" modals not being able to correctly read the token balance ( [8569b78](https://github.com/HathorNetwork/hathor-wallet/pull/395/commits/8569b78620e0ded7fa735f674a8c1b32139c107d) )
- "Change server" failures not raising messages on some cases ( [8bed03d](https://github.com/HathorNetwork/hathor-wallet/pull/395/commits/8bed03d81b2aba2d99c79e1f899dce936649b84e) )
- Unit test adjustments after merging the Atomic Swap interface PR ( [9ceeb24](https://github.com/HathorNetwork/hathor-wallet/pull/395/commits/9ceeb24ddd96ab979cbed56ce738d2dcc57196a2) )
- Fix …

fix: issues found on QA

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump to v0.26.0

---

src/sagas/tokens.js

- The fetching of proposal token metadata should happen within a channel with controlled concurrency queue

refactor: proposal token channel

---

src/__tests__/utils/atomicSwap.test.js
src/components/atomic-swap/ProposalBalanceTable.js
src/utils/atomicSwap.js

- Display `0.00` balance when a proposal has inputs and outputs for a token, but no change in the wallet balance.

fix: exhibition of swap with zero balance

---

README.md
RELEASING.md
scripts/check_version

- Create guides on how to sign and verify releases
- Fix in the check_version script so it considers the package-lock.json file
- Remove section from README.md about a warning in Windows that was already fixed
- https://bitcoincore.org/en/download/
- https://gnupg.org/download/integrity_check.html

docs: release signature guides

---

package-lock.json
package.json

chore: bump wallet-lib v1.0.1

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump version v0.27.0-rc2

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump version v0.27.0-rc3

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump version v0.27.0-rc4

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump v0.27.0-rc5

---

package-lock.json
package.json
public/electron.js
src/constants.js

- Bump version to v0.27.0 (remove release candidate)

chore: bump wallet to v0.27.0

---

public/electron.js
src/storage.js

- Implement a hybrid store based off `MemoryStore`

feat: Memory HybridStore

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump version v0.27.1-rc1

---

src/components/SendTokensOne.js

- Resolves the issue #443 
- Automatically removes whitespaces from the entered address to prevent errors during the transactions.

Fixes #443 - Automatically removes whitespaces from Addresses

---

src/sagas/wallet.js
src/storage.js

- Remove `wallet:id` methods
- Use access data in localStorage to check if we have a loaded wallet.

feat: remove `wallet:id` and use accessdata

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump v0.27.1-rc2

---

package-lock.json
package.json
public/electron.js
src/ErrorWrapper.js
src/components/SendTokensOne.js
src/constants.js
src/index.js
src/sagas/wallet.js
src/screens/LoadWallet.js
src/storage.js

Release v0.27.1-rc2

---

src/index.js
src/storage.js
src/utils/wallet.js

- Save access data when migrating from a previous version.

fix: save access data when migrating storage

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump v0.27.1-rc3

---

src/App.js
src/components/Navigation.js
src/screens/LockedWallet.js
src/screens/WalletVersionError.js

- The Locked screen should be a functional component
- The version error screen, only accessible through the Locked screen, should also be refactored
- The Navigation component can also be refactored, as it is displayed by the Locked screen on the `NavigationRoute` context

Refactor: Locked screen functional component

---

package-lock.json
package.json
public/electron.js
src/constants.js

- Bump wallet package to v0.27.1-rc4

chore: bump wallet to v0.27.1-rc4

---

package-lock.json
package.json
public/electron.js
src/App.js
src/components/Navigation.js
src/constants.js
src/screens/LockedWallet.js
src/screens/WalletVersionError.js
src/storage.js
src/utils/wallet.js

Release v0.27.1-rc4

---

src/screens/SendTokens.js

- Refactors the `SendTokens` screen to a functional component

refactor: `SendTokens` screen to functional component

---

src/components/SoftwareWalletWarningMessage.js
src/screens/LoadWallet.js
src/screens/NewWallet.js
src/screens/Signin.js
src/screens/SoftwareWalletWarning.js
src/screens/StartHardwareWallet.js
src/screens/WalletType.js

- Screens related to new wallets should be refactored to functional components

Refactor: New wallet screens to functional components

---

locale/texts.pot
src/screens/AddressList.js
src/screens/ChoosePassphrase.js
src/screens/Server.js
src/screens/Settings.js
src/screens/TransactionDetail.js

- Screens that are from the loaded wallet, but do not deal with transactions, should be refactored to functional components

Refactor: Admin screens to functional components

---

locale/texts.pot
src/screens/CreateNFT.js
src/screens/CreateToken.js
src/screens/CustomTokens.js
src/screens/NFTList.js
src/screens/UnknownTokens.js
src/utils/wallet.js

- Screens related to custom tokens should be refactored to functional components
- Fixes a small docstring that mentioned a promise return where the method was fully synchronous

Refactor: Custom token screens to functional components

---

src/sagas/featureToggle.js

- We should send the app version to unleash as a property so it can be filtered in feature toggle strategies

feat: send app version

---

release.sh

- Add environment versions to the release log.
- Add a quick fix for the Issue 484

chore(release): Add environment versions to the log and fix Issue 484

---

src/App.js
src/ErrorWrapper.js
src/components/ModalUnhandledError.js

- refactor: extract id selector to ModalUnhandledError component
- refactor: replace Route by useHistory hook to transmit history to App
- fix: navigation to /wallet_type path after remove device
Closes: https://github.com/HathorNetwork/internal-issues/issues/224

fix: forceful quit

---

src/App.js
src/sagas/wallet.js

- Fix listener cleanup for wallet listeners on redux-saga

feat: redirect on ledger lock

---

package-lock.json
package.json

- Updates jQuery to the latest stable version `3.7.1`
- All [release notes](https://blog.jquery.com/2023/08/28/jquery-3-7-1-released-reliable-table-row-dimensions/) mention there should be no impact on the upgrade.
- DevHub has [a page indicating a medium security issue with all versions of jQuery](https://devhub.checkmarx.com/cve-details/CVE-2014-6071/) for inputs, but since we use this lib only for handling modals it shouldn't be a problem to this application.

chore: Upgrades `jQuery`

---

src/screens/NewWallet.js
src/screens/Wallet.js

- On wallet screen update token info on any history change
- Mark wallet as opened when creating a new software wallet

feat: token info update

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump version v0.27.1-rc5

---

package.json
public/electron.js

- Add electron-debug command to increase dev convenience

chore: add electron-debug cmd and devtools extension options

---

QA.md
README.md
RELEASING.md

- Describe how to run an installed wallet in debug mode
- update expected node version on the docs

docs: debug mode on installed

---

SHORT_QA.md

- Add the details of the short qa.

docs: short qa

---

public/preload.js

- Clean localStorage when migrating a wallet that was initialized from a hardware wallet.
- Migrate important keys

fix: hardware wallet migration

---

QA.md

- Hardware wallet migration QA steps

docs: hardware wallet migration qa

---

.github/dependabot.yml
QA.md
QA_WALLET_SERVICE.md
public/electron.js
public/preload.js
src/App.js
src/components/GlobalModal.js
src/components/ModalConfirmClearStorage.js
src/components/RequestError.js
src/sagas/featureToggle.js
src/sagas/wallet.js
src/screens/SendTokens.js
src/screens/Server.js
src/screens/Wallet.js
src/storage.js
src/utils/helpers.js
src/utils/wallet.js

- Start the release process for v0.28.0

Start release-candidate for v0.28.0

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: bump v0.28.0-rc1

---

src/components/TokenBar.js
src/screens/UnknownTokens.js

- Remove token bar from unknown tokens screen
https://github.com/HathorNetwork/hathor-wallet/assets/15909384/9046bb33-18be-437b-82b8-c55054ea3d0f

fix: unknown tokens screen padding

---

package-lock.json
package.json
public/electron.js
src/constants.js

- Fix conflicts between release and master branches

Fix release 0.28.0 conflicts

---

package-lock.json
package.json

- Fixes the version for dependency `react-router-dom`, an oversight from #555
- No versions should change on the lockfile

Fix: Pin dependency version

---

package-lock.json
package.json
public/electron.js
src/constants.js

- Bumps version to `v0.28.1-rc.1`

Chore: Bump `v0.28.1-rc.1`

---

src/components/Navigation.js
src/constants.js

- Add feature flag for nano navigation with `false` as default

feat: add feature flag for nano in Navigation

---

package-lock.json
package.json
public/electron.js
src/constants.js

- Bumps version to `v0.28.1-rc.2`

Chore: Bump `v0.28.1-rc.2`

---

package-lock.json
package.json
public/electron.js
src/constants.js

chore: Bump v0.28.1

---

package-lock.json
package.json
src/index.js

While the release `0.28.1` was being made, a change was implemented on the version numbers on #605 . This created a conflict that had to be resolved manually through this PR.
- All conflicts between `master` and `release` should be resolved
- The `release` branch should be merged with `master`

[0.28.1] Merge release into master

---

flake.lock
flake.nix

- We should update all nix inputs to latest versions
- We should update nodejs to v20

chore: updated devshell, nodejs version and all inputs

---

src/actions/index.js
src/components/TokenBar.js
src/components/TokenGeneralInfo.js
src/reducers/index.js
src/sagas/wallet.js
src/utils/wallet.js

- Register any custom token that comes from the network `/version` api (under key `custom_tokens`).
- Always show the network tokens on the token bar

feat: show network tokens on token bar

---

src/actions/index.js
src/components/GlobalModal.js
src/components/nano/ModalConfirmUnregister.js
src/components/nano/ModalRegisterNanoContract.js
src/reducers/index.js
src/screens/nano/NanoContractDetail.js

- Add modal to unregister nano contract.
- Clean register nano metadata also on success.
https://github.com/HathorNetwork/hathor-wallet/assets/3298774/e7d16b62-7c1e-409c-9276-38ab6891168d

feat: unregister nano contract

---

src/App.js
src/actions/index.js
src/components/AddressList.js
src/components/GlobalModal.js
src/components/nano/ModalChangeAddress.js
src/components/nano/ModalConfirmUnregister.js
src/components/nano/ModalRegisterNanoContract.js
src/constants.js
src/index.module.scss
src/reducers/index.js
src/sagas/nanoContract.js
src/screens/AllAddresses.js
src/screens/nano/NanoContractDetail.js
src/storage.js

- Add Nano Contract Detail screen with attributes and available public methods to execute.
- Add Modal to change nano contract registered address.
- Refactor All Addresses screen to share a unique component with change address modal.
https://github.com/HathorNetwork/hathor-wallet/assets/3298774/a50997a6-e1be-437f-96bc-949d2fdccb29

feat: show nano contract detail

---

src/App.js
src/actions/index.js
src/components/AddressList.js
src/components/GlobalModal.js
src/components/nano/ModalChangeAddress.js
src/components/nano/ModalConfirmUnregister.js
src/components/nano/ModalRegisterNanoContract.js
src/constants.js
src/index.module.scss
src/reducers/index.js
src/sagas/nanoContract.js
src/screens/AllAddresses.js
src/screens/nano/NanoContractDetail.js
src/screens/nano/NanoContractSelectBlueprint.js
src/storage.js

- Add screen to select blueprint for creating a nano contract
https://github.com/HathorNetwork/hathor-wallet/assets/3298774/77704569-af77-415c-b323-559be6eb25aa

feat: add screen to select blueprint for creating a nano contract

---

src/components/TxData.js

- Show nano contract transaction details (nano contract ID, method name, arguments and caller).

feat: show nano contract detail of nc transaction

---

locale/texts.pot
src/App.js
src/actions/index.js
src/api/axiosInstance.js
src/components/AddressList.js
src/components/GlobalModal.js
src/components/TxData.js
src/components/nano/ModalChangeAddress.js
src/components/nano/ModalConfirmUnregister.js
src/components/nano/ModalRegisterNanoContract.js
src/constants.js
src/index.module.scss
src/reducers/index.js
src/sagas/index.js
src/sagas/nanoContract.js
src/sagas/wallet.js
src/screens/AllAddresses.js
src/screens/Server.js
src/screens/nano/NanoContractDetail.js
src/screens/nano/NanoContractList.js
src/screens/nano/NanoContractSelectBlueprint.js
src/storage.js
src/utils/nanoContracts.js
src/utils/version.js

- Add nano contract list screen.
- Add modal to register a nano contract.
- Add support for nano testnet network.
- HTTP 4XX errors shouldn't show error modal.
TODO: Missing wallet lib bump to v1.6.0 with `getRegisteredNanoContracts` method
https://github.com/HathorNetwork/hathor-wallet/assets/3298774/29af27e3-7b44-444a-86fb-549ae77bb805

feat: add nano contract list and modal to register a nano

---

package-lock.json
package.json

- Start release-candidate process for v0.29.0-rc.1
- #528
- #606
- #607 
- #605 
- #608 
- #622 
- #626 
- #632 
- #633 
- #636 
- #639 
- #638 
- #529

chore: bump to v0.29.0-rc.1

---

package-lock.json
package.json

Start release-candidate process for v0.29.0-rc.1
- #645

chore: bump to v0.29.0-rc.2

---

src/screens/CreateNFT.js
src/screens/CreateToken.js

- Fix unwanted symbol prefix on CreateToken and CreateNFT

fix: unwanted-symbol-prefix

---

package-lock.json
package.json

- Bump to v0.29.0
Release: https://github.com/HathorNetwork/hathor-wallet/pull/649

chore: bump package to v0.29.0

---

src/index.module.scss
src/screens/nano/NanoContractDetail.js

- Show list of balances of a nano contract in the Nano contract detail screen

feat: show nano contract balances in the transaction detail screen

---

.github/workflows/e2e.yml
.github/workflows/main.yml

- upgrade actions to a version that use node20 (LTS)

chore: upgrade actions to a version that use node20 (LTS)

---

src/components/nano/NanoContractHistory.js
src/constants.js
src/index.module.scss
src/screens/nano/NanoContractDetail.js

- Add nano contract transaction history list to the nano contract detail screen
Note: The list in the video has only 3 elements because it was better to demonstrate but it will have 5 elements.
Note 2: The list doesn't have real time update as the explorer. We will debate to have real time update for the nano state and list history in another moment.
https://github.com/user-attachments/assets/9d5b067c-48af-49a5-b94f-f2038ebeef33

feat: add nano contract transaction history list to the nano detail screen

---

package-lock.json
package.json

- Continues release process for v0.30.0-rc.1 started at #668

bump: v0.30.0-rc.1

---

package-lock.json
package.json

- update hathor lib to v1.14.1

chore: update lib to v1.14.1

---

package-lock.json
package.json

bump: v0.30.0-rc.2

---

RELEASING.md

- Update the process description on `releasing.md`
- It should match the improvement made on #605

docs: Updates process description

---

package-lock.json
package.json

chore: Bump to v0.30.0

---

src/actions/index.js
src/components/Navigation.js
src/reducers/index.js
src/sagas/wallet.js

- Consider full node flag to enable nano contract to show/hide Navigation.

feat: show nano contract navigation only if full node also supports it

---

package-lock.json
package.json

- Bump version to v0.30.1-rc.1

chore: bump release candidate v0.30.1-rc.1

---

src/index.module.scss
src/screens/nano-contract/NanoContractDetail.js

- Improve UI when nano contract has many public methods available
Old UI:
New UI:

style: improve nano methods style for many available methods

---

package-lock.json
package.json

chore: Bump 0.30.1

---

QA_Nano.md

See [rendered](https://github.com/HathorNetwork/hathor-wallet/blob/docs/nano-tests/QA_Nano.md)
- There should be a new document for testing the Nano Contracts screens

docs: New QA doc for nano

---

package.json
release.sh

chore: add build for linux arm64

---

package-lock.json
package.json

chore: bump v0.31.0-rc.1

---

package-lock.json
package.json

chore: bump v0.31.0-rc.2

---

package-lock.json
package.json

chore: bump to 0.31.0-rc.3

---

package-lock.json
package.json

chore: bump v0.32.0 rc.1

---

package-lock.json
package.json

chore: bump v0.32.0

---

src/actions/index.js
src/components/NetworkSettingsForm.js
src/constants.js
src/reducers/index.js
src/sagas/featureToggle.js
src/sagas/networkSettings.js
src/screens/Settings.js
src/utils/helpers.js

- Update unleash client context on network settings change

feat: update unleash context on network change

---

package-lock.json
package.json
src/actions/index.js
src/reducers/index.js
src/sagas/wallet.js
src/screens/LoadWalletFailed.js

- Add reset and connect to mainnet buttons on load fail
https://github.com/user-attachments/assets/a30adc5e-3255-4f14-bc89-bc65b603d3b8

feat: add reset and connect to mainnet button on load fail
