HathorNetwork/hathor-wallet

- package.json
- src/App.js
- src/storage.js
- src/utils/tokens.js
- src/utils/version.js
- src/utils/wallet.js
hathor-wallet-lib now requires to be given a storage.
Also, the lib used to open the websocket connection when it was imported. This was changed and we need to manually start websocket connection.
> refactor: storage

- src/components/ServerStatus.js
Starting with `testnet-bravo`, testnet names have a suffix. Now we should check if the name starts with "testnet" to add the warning class.
> fix: testnet warning css class

- src/components/TokenBar.js
Using - as separator could mislead the user to think that it was a negative value. Changed to | as separator.
Old screen:
New screen:
Closes #79
> style: changing token bar symbol/value separator from - to |

- src/components/SendTokensOne.js
- Show available balance;
- Update balance when changing token;
- Update balance on real time when new tx arrives.
Old screen:
New screen:
Closes #67
> feat: show available balance on send tokens screen

- public/entitlements.mac.plist
Closes #97 
I had to add 2 entitlements to resolve 2 different problems:
(1) After I upgraded macOS to Mojave 10.14.6, I had this issue: https://github.com/electron-userland/electron-builder/issues/3940
(2) Final Electron app could not communicate with Ledger, like here: https://github.com/LedgerHQ/ledgerjs/issues/439. The problem was actually in a dependency: https://github.com/node-hid/node-hid/issues/321
> fix: ledger communication on Electron release

- package-lock.json
- package.json
- src/App.js
- src/components/HathorPaginate.js
- src/components/Navigation.js
- src/components/WalletAddress.js
- src/index.scss
- src/screens/AddressList.js
- src/screens/Wallet.js
Unresolved questions:
1. Should we have a new item on the menu? At first I tried to add some link/button close to the address box in the main wallet screen but none of my attempts were good, so I just added this new menu.
2. I created a new pagination because we already have all the elements on the list and I always think it's better to have all the pages there (if it's possible). Should we keep the same pagination as in the other screens with 'Previous'/'Next'?
3. Should we show all addresses including the ones from the `GAP_LIMIT`. I think we should because maybe the user has generated new addresses, sent to someone but still haven't received the txs, in that case none of those addresses would appear on the list. However, showing all addresses might be confusing to the user.
> feat: List of addresses from the wallet

- src/screens/LoadingAddresses.js
Closes #106. changes summary: added background for loading addresses screen.
> feat: add background image for loading addresses screen

- QA.md
- src/App.js
Steps to reproduce:
1. Go to some initial screen (not the welcome) before loading the wallet (e.g. backup screen);
2. Close the wallet app;
3. Open the wallet, then it will start on  wallet type screen (to select between software and hardware wallet)
> fix: user shouldnt be able to see wallet type screen for now

- package.json
* `npm run electron-dev` now runs `npm start` concurrently with `wait-on && electron`. It will automatically open electron after 'http://localhost:3000' is available
* `npm run electron-deps` now runs on `postinstall` hook
> chore: use wait-on concurrently with electron

- package-lock.json
- package.json
Bump `wallet-lib` to solve an issue related to importing wallet.
<table>
<thead>
<tr>
<th>Before bump (can't proceed with the importing):</th>
<th>After bump:</th>
</tr>
</thead>
<tbody>
<tr>
<td><img src="https://user-images.githubusercontent.com/5104565/101706838-bbff1b80-3a68-11eb-879e-31cb6308dd91.gif" /></td>
<td><img src="https://user-images.githubusercontent.com/5104565/101706871-d3d69f80-3a68-11eb-809b-f41ef3047b8f.gif" /></td>
</tr>
</tbody>
</table>
> chore: bump lib version to v0.16.5

- src/screens/Settings.js
The main purpose of this feature is to help debug some timestamp issues we've been having.
Question: Should we show in this format? I like showing the full date/time and timezone. I could remove the weekday only but I left because it's not worse with it in my opinion.
> feat: show local date and time in settings screen

- src/reducers/index.js
This line was removed by mistake in the last PR: https://github.com/HathorNetwork/hathor-wallet/pull/188/files#diff-3d74dddefb6e35fbffe3c76ec0712d5c416352d9449e2fcc8210a9dee57dff67L157
> fix: set wallet version on storage before running version check

- package-lock.json
- package.json
A change on package-lock.json (adding the wallet-lib dependencies inside the wallet-lib object instead of outside) created a bug when signing a transaction. The bitcore lib was not being installed correctly.
- Fix package-lock.json in order to install bitcore lib correctly and the input signatures continue working.
> fix: package lock rollback for node v8.9.0 format

- src/App.js
- src/constants.js
- src/index.scss
- src/screens/CreateNFT.js
- src/screens/CustomTokens.js
- src/utils/tokens.js
- User must be able to create an NFT using the wallet desktop. He must be able to customize it selecting the data string, the address, name, symbol, amount and if he would like to create mint/melt authorities
- The screen must make it clear for the user the deposit and fee required for minting an NFT
> feat: add support for creating NFT

- src/index.scss
When we have more tokens registered than it fits on the screen, then we must have a scroll in the token bar for accessing all the tokens.
Fixes #226
> fix: add vertical scroll for token bar body

- QA.md
- package-lock.json
- package.json
- src/components/tokens/TokenDelegate.js
- src/components/tokens/TokenDestroy.js
- src/components/tokens/TokenMelt.js
- src/components/tokens/TokenMint.js
- src/screens/CreateNFT.js
- src/screens/CreateToken.js
- src/screens/SendTokens.js
In the wallets we prefer to handle every step of the `SendTransaction` flow to show a better information for the user in the screen. Because of that, we are using this class directly which now requires one more parameter because of https://github.com/HathorNetwork/hathor-wallet-lib/pull/276.
We must send `network` when creating `SendTransaction` object to validate the addresses.
> feat: SendTransaction class now requires network parameter to validate the address of transaction

- locale/texts.pot
- src/components/ModalResetAllData.js
- Form should ignore the password field if the "Forgot password" checkbox is selected.
- Fixes #246 
**When the "Forgot Password" checkbox is selected, the "Password" field is cleared and disabled.**
[Example video](https://user-images.githubusercontent.com/1299409/149586640-4f10fcec-36f9-488b-b958-d309e5ec0987.mp4)
**When the user closes the modal, all its fields are cleared.**
https://user-images.githubusercontent.com/1299409/149586712-ec26344c-677f-4264-8860-e3eff63e6c44.mp4
> fix: ignoring password when user forgot it on wallet reset

- src/App.js
- When a software wallet setup was not completed, the app should open on "Wallet Type" screen after restarting
- Fixes #233
> fix: select wallet type after selecting "software" and restarting

- package-lock.json
- package.json
- src/components/TxData.js
- On "Transactrion Details" screen, data scripts should be shown correctly and not 'Unable to decode'.
- Specifically NFT creation transactions must show their script output correctly
- Resolves #265 
**Old screen**
**New screen**
This feature is similar to the Explorer's PR 141: HathorNetwork/hathor-explorer#141
Hathor Wallet Lib dependency updated to 0.29
> feat: displaying correct script data on tx details screen

- src/components/NFTListElement.js
We've added support in the explorer NFT preview to read `mime_type` data from the metadata file to better show the videos and audios preview (https://github.com/HathorNetwork/hathor-explorer/pull/160). We must add this support in the wallet as well because some of the previews are working on the explorer but not in the wallet
- Show NFT preview that rely on the mime type
> feat: add support for showing NFT reading metadata mime type

- package-lock.json
- package.json
- upgrade `@hathor/wallet-lib` to v0.33.1
> chore: bump wallet lib v0.33.1

- src/components/TokenAdministrative.js
- src/screens/Wallet.js
The wallet-service did not have the `getMintAuthority` and `getMeltAuthority` methods, they have been added on **this PR**, so this PR is the implementation of those methods on the wallet-desktop
- We should use the `getMintAuthority` and `getMeltAuthority` from the [new normalized method on both facades](https://github.com/HathorNetwork/hathor-wallet-lib/pull/344)
> feat: get mint melt authority from new facade methods

- src/index.scss
- src/screens/LockedWallet.js
Currently, we allow the user to click multiple times on the "Unlock" button on the LockedWallet screen, this causes the app to trigger multiple requests when on the wallet-service facade.
https://user-images.githubusercontent.com/3586068/163487704-df08402b-f8bc-42ef-b3c0-24e8898d6916.mov
- The Locked Wallet screen should display a loading on the Unlock button and prevent multiple calls to `startWallet` if the user presses the button multiple times
> feat: loading on locked wallet button

- src/components/TokenAdministrative.js
- src/components/TokenGeneralInfo.js
- src/screens/LockedWallet.js
Currently, our wallet desktop is querying the fullnode for token details, we should use the same method on both facades to query this information from the wallet-service (if on the facade) or the full-node. This new method [has been created on the wallet-lib](https://github.com/HathorNetwork/hathor-wallet-lib/pull/345) to utilize the token info API, [created on the wallet-service](https://github.com/HathorNetwork/hathor-wallet-service/pull/202)
- The wallet desktop should query the wallet service for token details when on the wallet service facade
- The wallet desktop should use the `getTokenDetails` method from the wallet facades to query token information
> feat: wallet service token details

- src/utils/wallet.js
To avoid doing multiple requests to the `tx_history` API, we should download more transactions from the transaction history API 
- After https://github.com/HathorNetwork/hathor-wallet-service/pull/208 is merged, we should be able to request 50 transactions from the tx history API
> refactor: revert tx history size initial download

- locale/texts.pot
- package-lock.json
- package.json
- src/actions/index.js
- src/components/ModalSendTx.js
- src/components/SendTxHandler.js
- src/components/TokenAdministrative.js
- src/components/TokenGeneralInfo.js
- src/components/TokenHistory.js
- src/components/WalletAddress.js
- src/components/tokens/TokenDelegate.js
- src/components/tokens/TokenDestroy.js
- src/components/tokens/TokenMelt.js
- src/components/tokens/TokenMint.js
- src/constants.js
- src/featureFlags.js
- src/index.scss
- src/reducers/index.js
- src/screens/CreateNFT.js
- src/screens/CreateToken.js
- src/screens/LockedWallet.js
- src/screens/SendTokens.js
- src/screens/Settings.js
- src/screens/Wallet.js
- src/utils/helpers.js
- src/utils/wallet.js
- To be able to load the wallet from xpriv (that's what the wallet desktop uses after a re-open), we had to start storing a xprivkey on the account level derivation on `localStorage`, this is done on the [wallet-lib PR](https://github.com/HathorNetwork/hathor-wallet-lib/pull/342)
- We are using a random string as the application's unique identifier for Unleash, storing it on local storage to persist it between reloads
- We are only setting the current address on the wallet screen after we reload the addresses after a create token or send token transaction is done. This causes the address to be empty after sending a transaction until this transaction is received from websocket
- We don't yet have a count of authorities coming from the wallet service API so we are displaying a hardcoded …
> feat: wallet service integration on the desktop wallet

- locale/texts.pot
- src/components/ModalAddManyTokens.js
- src/components/ModalAddToken.js
- src/components/TokenBar.js
- src/components/TokenGeneralInfo.js
- src/screens/CustomTokens.js
- src/screens/Settings.js
- src/screens/UnknownTokens.js
- src/screens/Wallet.js
- src/utils/wallet.js
This feature adds a new option in the wallet settings, “Hide zero-balance tokens”. When checked, any tokens with a balance of zero would not be displayed anywhere in the wallets.
- When “Hide zero-balance tokens” is checked, any tokens without a balance should be hidden everywhere in the wallet.
- If the user unchecks the option again, they should be shown.
- User should be allowed to register zero-balance tokens even if the flag is active.
- User should be able to create exceptions for selected tokens ( "Always show" flag )
The video below shows a wallet with registered and unregistered tokens with zero balance. When the "hide" flag is activated on the settings screen, those tokens are hidden from the user on all screens.
https://user-images.githubusercontent.com/1299409/167445861-fc63d09 …
> feat: option to hide zero-balance tokens

- public/electron.js
- src/components/ModalLedgerSignToken.js
- src/screens/WalletType.js
- Enable Ledger to work with upgraded dependencies
To communicate with Ledger we use a library to send/receive data to the USB port and the version we currently use of this library cannot run on the renderer process. So we run any call to Ledger on the main process and use the `electron.IpcRenderer` to send and receive events between the main process and the renderer process.
On electron version 12 a breaking change was introduced ([changelog here](https://www.electronjs.org/docs/latest/breaking-changes#default-changed-contextisolation-defaults-to-true)) that changed the default of the `contextIsolation` which (among other things) enables or disables the use of `require` to import node packages on the renderer process, including the 'electron' package itself.
Once we disabled the …
> chore: enable require on renderer process

- src/components/ModalResetAllData.js
- src/screens/Settings.js
Many users have hundreds of tokens and, when they reset their wallets, or change devices, they must register all of them again. We already have in the desktop wallet the possibility of a bulk import in the Unknown Tokens screen, we only needed a feature to export all registered tokens, so the users won't have to register all of them again.
- Users should be able to export the configuration strings of all registered tokens
https://user-images.githubusercontent.com/3298774/176432891-98d8d429-b338-43b0-8463-4fd6c613615d.mov
- Following @tuliomir's suggestion (https://github.com/HathorNetwork/hathor-wallet/pull/331#issuecomment-1170330708) I've added a message in the reset modal about the export tokens feature.
> feat: add feature to export configuration strings for registered tokens

- src/screens/CreateNFT.js
- src/utils/wallet.js
When a user creates an NFT, the application creates a simplified version of the NFT metadata locally instead of waiting for the `explorer-service`'s response with the complete metadata.
The wallet service's response will still override the simplified local version, but the user will have the improved NFT experience immediately.
- Show newly-created NFT's correct type on the token screen
----- 
**Before: Custom token exhibition**
-----
**After: NFT Exhibition**
-----
> feat: update local storage with metadata on nft creation

- src/actions/index.js
- src/components/WalletAddress.js
- src/reducers/index.js
- src/sagas/wallet.js
- src/screens/SendTokens.js
- fix: making sure that we are closing the modal on unmount
- fix: storing routerHistory on redux state
- feat: add selected token as default transaction to send
- Set the active token in the wallet sidebar as the default token in the "Send tokens" page
> feat: select active token as default to send

- codecov.yml
- src/actions/index.js
- src/sagas/helpers.js
- src/sagas/wallet.js
- src/utils/helpers.js
- We should handle errors in the `startWallet` saga, allowing the user to retry the request
- We should fix an error where the wallet would break (and reset) when initializing on the wallet-service
- The `walletUtils.reloadElectron` method was broken, I removed it and added a mechanism for starting the wallet using the saga again
> fix: restart after wallet service error using saga

- package-lock.json
- package.json
- Upgraded wallet-lib to v0.43.0
> chore: upgraded wallet-lib to v0.43.0

- ELECTRON.md
- package.json
- release.sh
- scripts/win-ev-sign.js
- Sign Windows executable using an EV Code Signing Certificate in a YubiKey.
> chore: Tools for Windows release with EV Code Signature from YubiKey

- src/sagas/wallet.js
- We should refresh the wallet facade addresses on its internal state when the wallet is reloaded
- We should show the loading screen until the addresses are refreshed
> fix: refresh addresses on reload

- .github/workflows/e2e.yml
- src/constants.js
- src/featureFlags.js
- src/utils/helpers.js
This is the new configured feature flag in unleash: 
- We should pass the network as the `stage` property when updating unleash context to make use of the [new wallet-desktop feature flag](https://unleash.internal.hathor.network/projects/default/features/wallet-service-desktop.rollout)
> refactor: using new feature flag schema

- src/__tests__/components/ModalPin.test.js
- src/__tests__/components/ModalSendTx.test.js
- src/components/GlobalModal.js
- src/components/ModalPin.js
- src/components/ModalSendTx.js
- src/components/PinInput.js
- src/components/SendTxHandler.js
- src/components/tokens/TokenAction.js
- src/screens/CreateNFT.js
- src/screens/CreateToken.js
- src/screens/SendTokens.js
- src/utils/helpers.js
The PIN modal we currently have also has the logic to send transactions after receiving the user input. To make it more reusable in other contexts, a dedicated PIN modal should be created with the existing code.
- Creates a `ModalPin` component dedicated only to receiving PIN input from the user
- The PIN logic should be removed from the `ModalSendTx` where it currently is
- Screens that used the `ModalSendTx` modal should continue working as expected, sending transaction and being informed of success or error
The current implementation has a seamless state change between the PIN input and the monitoring of the transaction send status. This refactor separates the logic into two modals, creating a noticeable modal change between steps.
**Failure handling** …
> refactor: Dedicated pin modal

- package-lock.json
- package.json
- public/electron.js
- src/App.js
- src/actions/index.js
- src/components/ModalUnregisteredTokenInfo.js
- src/constants.js
- src/reducers/index.js
- src/sagas/helpers.js
- src/sagas/wallet.js
- src/screens/LockedWallet.js
- src/screens/Wallet.js
- src/utils/storage.js
- Include HTR in the registered tokens
- Update registered tokens when starting a wallet
- When first starting the wallet we should migrate the localStorage to the new keys, so we can start from the same point that the wallet would start on the previous version./
- mark the wallet as opened when we open the wallet
- Pass the storage as prop to ModalUnregisteredTokenInfo, so it can unregister the token.
- bump the version to 0.27.0-rc1
> feat: register HTR on start saga

- package-lock.json
- package.json
- src/reducers/index.js
- src/sagas/wallet.js
- src/screens/LoadWallet.js
- src/screens/Server.js
- src/screens/TransactionDetail.js
- src/storage.js
- src/utils/wallet.js
- Use the correct methods to change the server and ws server
- When changing networks, clean the registered tokens as well.
> fix: change server

- src/reducers/index.js
- When unregistering zero balance tokens it keeps showing as `unknow tokens`, i.e. tokens with balance on the wallet that was not registered.
> chore: fix UI issues with unknown tokens

- .github/workflows/e2e.yml
- Stop running e2e tests until they are fixed
- Upgrade e2e actions versions
> chore: stop e2e tests

- .github/dependabot.yml
- Dependabot analysis should be run against the `dev` branch
Besides the base branch definition, the Dependabot [configuration docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#target-branch) also mentions other properties that could be useful to us, such as personalized labels. So, this PR also adds these other properties.
> Chore: Dependabot config

- src/App.js
- src/components/Version.js
- src/constants.js
- src/sagas/wallet.js
- src/screens/SendTokens.js
- src/screens/Server.js
- src/screens/Welcome.js
- src/storage.js
[qa issue](https://github.com/HathorNetwork/internal-issues/issues/191)
- `getSignatures` util for ledger expects a wallet instance but was receiving a storage instance.
- Clean only needed keys on storage to redirect user to wallet_type instead of welcome when opening the wallet.
- await `preparingTxfrom` so that the transaction is ready when we push it to the network.
> chore: fix ledger issues found during QA v0.27.0-rc4

- src/screens/Settings.js
- To show the 'Untrust All Tokens' button we must have `LOCAL_STORE.isHardwareWallet()` as `true`, because it means that the ledger is in use.
> fix: show untrust all tokens option

- package-lock.json
- package.json
This upgrade removes some obsolete indirect dependencies that were interfering with an upgrade to Node.js `v20`
- Upgrades [`unleash-proxy-client`](https://github.com/Unleash/unleash-proxy-client-js) to the latest stable version `3.2.0`
On `v2.0.2` [release](https://github.com/Unleash/unleash-proxy-client-js/releases/tag/v2.0.2-beta-0) it was announced that this lib will no longer support natively `react native async storage`. This native support was precisely what was breaking our migration, so it is a welcome change for this repository.
> Chore: Update `unleash-proxy-client`

- src/ErrorWrapper.js
- src/index.js
- src/screens/LoadWallet.js
In the process to update React Router to v6, it is first necessary to make the current implementation of v5 fully integrated with react hooks. ( see: [official docs](https://reactrouter.com/en/main/upgrading/v5#upgrade-to-react-router-v51) )
- Refactor the Router `root` element for React to use React v18
- Refactor the `ErrorWrapper` to be a _functional component_ and use hooks
- Refactor the `ErrorWrapper` to be a direct child of the root router
> Refactor: Navigation root for Router v5

- package-lock.json
- package.json
- public/ledger.js
- public/preload.js
- src/App.js
- src/screens/StartHardwareWallet.js
- src/storage.js
- src/utils/wallet.js
Fix the issues described in #473
- Update ledger transport dependency
- Update hathor wallet lib dependency
- Do not redirect to locked screen when starting a hardware wallet
- During preload, clean any previous hardware wallet access data.
- Add better logs to debug issues with ledger communication
> fix: unresponsive ledger device

- package-lock.json
- package.json
- Updates the QRCode library
There were [no breaking changes](https://github.com/zpao/qrcode.react/releases/tag/v3.0.0) on the upgrade from `0.9.3` to `3.1.0`. The `qr.js` sub-dependency was also removed.
> Chore: Update `qrcode`

- flake.nix
`libusb1` is now a dependency for one of the libraries the wallet-desktop uses, we should have it in the dev environment
> chore: add libusb1 to flake

- src/screens/Wallet.js
- The `wallet` screen should be refactored to a functional component
> Refactor: `wallet` screen to functional component

- package-lock.json
- package.json
Even though we want to use typescript on this application some day, it's currently unused and can be safely removed during this dependencies upgrade process. It was first added as a dev dependency on #32 
The application without this dependency was tested successfully in:
- Development environment
- The build artifacts
- The distributable binaries for Linux
- Removes the `typescript` dependency
> chore: Removes `typescript`

- package-lock.json
- package.json
- Upgrades `nodemon` to the latest stable `v3.0.3`
Update from 2.0.16 to 3.0.3
- [v3](https://github.com/remy/nodemon/releases/tag/v3.0.0) only deprecates usage of node@8
> chore: Upgrades `nodemon`

- package-lock.json
- package.json
- Upgrades `sass` from `v1.52.2` to `v1.70.0`
No major versions were upgraded, so no breaking changes.
> chore: Upgrades `sass`

- package-lock.json
- package.json
- Upgrades `react-paginate` to v8.2.0
The [changelogs](https://github.com/AdeleD/react-paginate/blob/v8.2.0/CHANGELOG.md#-820) for this dependency indicate no breaking changes
> chore: Upgrades `react-paginate`

- package-lock.json
- package.json
- Upgrades `ttag` to v1.8.6
- There are no release notes since 2017 [on the repo's GitHub](https://github.com/ttag-org/ttag/releases)
- There are also no change logs [on their official site](https://ttag.js.org/docs/changelog.html) since 2019
- [The commits themselves](https://github.com/ttag-org/ttag/commits/v1.8.6/) indicate no suspicious activity: and only valid patches and fixes and a refactor to TypeScript
> chore: Upgrades `ttag`

- package-lock.json
- package.json
- Upgrades `@sentry/browser` to the latest stable `v7.99.0`
- Upgrades `@sentry/cli` to the latest stable `v2.27.0`
**Browser** update from 5.30.0 to 7.99.0
- [v6](https://github.com/getsentry/sentry-javascript/releases/tag/6.0.0) has no breaking changes
- [v7](https://github.com/getsentry/sentry-javascript/releases/tag/7.0.0) has some, but do not affect this application usage
**Cli** update from 1.74.4 to 2.27.0
- [v2](https://github.com/getsentry/sentry-cli/releases/tag/2.0.0) has some breaking changes, but none related to our usage on `/upload_source_maps.sh`
> chore: Upgrades `sentry`

- package-lock.json
- package.json
- Upgrades `jsdoc` from version `3.6.10` to `4.0.2`
- [version 4.0.0](https://github.com/jsdoc/jsdoc/blob/main/CHANGES.md#400-november-2022) removes a subdependency on `taffydb`, replacing it with `salty`. This does not affect the wallet application.
- The [commits up to 4.0.2](https://github.com/jsdoc/jsdoc/commits/4.0.2/) are not present on the releases or changelogs, but do not include any breaking changes
> chore: Upgrades `jsdoc`

- .github/dependabot.yml
- DependaBot must suggest its changes to the `master` branch after our new release process
This an update to the configurations made on #424
> chore: Updates dependabot branch

- src/components/RequestError.js
- src/sagas/wallet.js
- src/screens/Server.js
- src/storage.js
- src/utils/wallet.js
Three user behaviors related to network changes were triggering crashes on the application and were fixed.
- Selecting a custom token and changing the network should not crash with an "Invalid Token" error ( [1e91a0a](https://github.com/HathorNetwork/hathor-wallet/pull/537/commits/1e91a0af1536f3d4086524187d4d1404aaec0e1e) )
- When recovering from being offline, the application tried to call a discontinued lib method and crashed ( [1d854c4](https://github.com/HathorNetwork/hathor-wallet/pull/537/commits/1d854c4c2c42c30b4455955f7264624db4478a91) )
- Unused methods cleanup ( also on [1d854c4](https://github.com/HathorNetwork/hathor-wallet/pull/537/commits/1d854c4c2c42c30b4455955f7264624db4478a91) )
- When resetting the wallet while on testnet, the lib configuration object became inconsistent …
> Fix: Server change issues

- src/sagas/wallet.js
This is a complement of #537 : , it fixed all tested cases for software wallets. However when testing hardware wallets on `testnet` some new errors appeared. This PR fixes them.
The cause is that the _network name_ was never updated on local store for a hardware wallet.
- The application should run a hardware wallet successfully on `testnet`
- After closing and opening the application again, the application should not throw any errors and continue on `testnet`
> fix: Network name inconsistency

- src/screens/SendTokens.js
- src/screens/Wallet.js
The ledger modal was deciding its rendering state based on a component state that was not being updated correctly after the refactor on #483 .
The code was changed to decide the rendering based on function parameters instead of component states, so that the correct context is always provided directly. Also, the `txData` local variable was completely removed and re-calculated whenever necessary to reduce component complexity.
Because this transaction data parameter needed to be handled in the Ledger event handlers, a workflow that is different from the one of the component rendering, the `sendTransaction` variable was moved outside the component. 
- The Ledger modal should work on the full transaction send flow
- Minor function name refactorings should make their responsibilities clearer …
> fix: Ledger modal not updating on SendTokens

- public/electron.js
- src/App.js
- src/components/GlobalModal.js
- src/components/ModalConfirmClearStorage.js
- src/components/ModalConfirmReset.js
- Create a menu that offers the possibility to reset all wallet data for the user
> Normal call to reset
https://github.com/HathorNetwork/hathor-wallet/assets/15909384/ddf53d0f-8e00-4c81-9fc9-87cac17131c0
> Calling to reset during a bug
https://github.com/HathorNetwork/hathor-wallet/assets/15909384/ffeaffff-c88d-441d-bfaf-cea835ae4233
> feat: reset data menu

- src/sagas/wallet.js
- Do not fetch HTR token metadata from the explorer-service.
> feat: filter HTR out when fetching token metadata

- src/App.js
- src/actions/index.js
- src/reducers/index.js
- src/sagas/atomicSwap.js
- src/sagas/wallet.js
- src/screens/ChoosePassphrase.js
- src/screens/LoadWallet.js
- src/screens/LockedWallet.js
- src/screens/NewWallet.js
- src/screens/Server.js
- src/screens/StartHardwareWallet.js
- src/utils/wallet.js
The next version of Redux throws an error by default whenever there are non-serializable objects in its Store ( more about this on [this article](https://www.bam.tech/article/the-redux-best-practice-do-not-put-non-serializable-values-in-state-or-actions-explained) ). This PR is one in a series of PRs that aim to refactor all of those instances before the upgrade.
The `routerHistory` property stored is currently used for navigating inside our Sagas. The proposed solution is to:
- Create a `navigateTo` property on the store
- Create a `useEffect()` inside the `App.js` screen listening to changes on this property
- `App.js` becomes responsible for navigating whenever a background task requests it to
- The `routerHistory` should not be present on the Redux Store
> Refactor: Removes `routerHistory` from Redux store

- src/components/ModalUnhandledError.js
- src/components/TxData.js
Two instances of navigation calls were missed during the refactor of #555 . Those should be corrected so that all navigation calls work accordingly.
- All navigation requests within the application should use the `useNavigate` hook
Since the `ModalUnhandledError` component is quite simple, I took the opportunity to also refactor it to a functional component. The `TxData` component, however, is complex enough to deserve its own PR in a future moment, so I only made the smallest adjustment to fix the issue.
> Fix: Missing navigation calls

- package-lock.json
- package.json
- src/store/index.js
This PR upgrades the Redux version of this application from `v4` to `v5`, but instead of keeping it a direct rependency, replaces it with `redux-toolkit` that indirectly uses `redux`. This is [the strongly recommended](https://redux.js.org/style-guide/#use-redux-toolkit-for-writing-redux-logic) approach by the current Redux docs.
This is the first step needed for the broader refactoring of the redux code proposed by #507 , aiming to bring this code to more up to date best practices for Redux.
- Upgrades the `Redux` dependency
> chore: Upgrades `redux`

- src/index.js
- The production build of the application within Electron should work correctly
After the upgrade to React Router v6 ( #555 ) our production-built router stopped working: all requests were being redirected to the 404 page.
Upon investigation it was identified that the router's `location.pathname` was being retrieved with the full file path ( ex.: `/tmp/.mount_HathorUnoEsq/resources/app.asar/build/index.html/welcome` ) instead of a relative path from the root of the application ( ex.: `/welcome` ).
Some issues[^1][^2] within the React repository, articles[^3] and SO answers[^4] indicate that switching the router type is a reasonable solution. There is a possibility of configuring the `BrowserRouter` to work with the Electron production builds, but that would involve more research, trial …
> fix: Router for Electron on release build

- src/screens/LockedWallet.js
If the wallet is locked while the screen is scrolled down, the `LockedScreen` is also loaded scrolled, hiding its visual elements. This PR fixes this.
- Everytime the `LockedScreen` is loaded, all elements should be visible
> feat: Scroll to top on `LockedWallet`

- src/actions/index.js
- src/components/ChoosePassword.js
- src/components/ChoosePin.js
- src/reducers/index.js
- src/screens/LoadWallet.js
- src/screens/NewWallet.js
This PR removes the Pin and Password information from Redux, and instead keeps it in the smallest scope possible within the component state of the `NewWallet` and `LoadWallet` screens.
This avoids any future bugs where the Redux store cleanup fails or even security issues should the Redux store happen to leak.
- Pin and Password should never be stored on Redux
To facilitate the refactor, the `ChossePassword` and `ChoosePin` components were refactored to functional components.
> refactor: Removes pin and password from Redux

- locale/texts.pot
- src/actions/index.js
- src/components/ModalBackupWords.js
- src/reducers/index.js
- src/screens/LoadWallet.js
- src/screens/NewWallet.js
- src/screens/Wallet.js
- src/screens/WalletVersionError.js
This PR removes the Seed Words from Redux, and instead keeps it in the smallest scope possible within the component state of the `NewWallet` and `ModalBackupWords` screens.
This avoids any future bugs where the Redux store cleanup fails or even security issues should the Redux store happen to leak.
- The seed words should never be stored on Redux
The translations file also had to be updated, as there were changes to the screen component files.
> refactor: Remove seed words from Redux

- .github/workflows/release-merge.yml
This is the first version of this automation, with a simple PR creation to ensure the merge is always done for each new public version of the application.
- Creates a new workflow to automatically merge `release` into `master` whenever a public version is released
This requires specific permissions on the workflow GitHub Token, so will be implemented and tested separately
This requires parsing specific text syntax from [`CODEOWNERS`](https://github.com/HathorNetwork/hathor-wallet/blob/master/.github/CODEOWNERS). So this will be done after the simplest solution is operational.
This workflow will be the best place to implement this solution, but will be done at a later moment to allow for a quick release now
> feat: Workflow to automatically merge `release` into `master`

- locale/texts.pot
- package-lock.json
- package.json
- src/actions/index.js
- src/components/TokenAdministrative.js
- src/components/TxData.js
- src/components/tokens/TokenMint.js
- src/reducers/index.js
- src/sagas/wallet.js
- src/screens/CreateNFT.js
- src/screens/CreateToken.js
- src/screens/CustomTokens.js
- src/screens/Server.js
- src/screens/Settings.js
- src/screens/TransactionDetail.js
- src/screens/Wallet.js
- src/screens/Welcome.js
- src/utils/atomicSwap.js
- src/utils/tokens.js
- src/utils/wallet.js
- Remove all uses of `HATHOR_TOKEN_CONFIG` in favor of `NATIVE_TOKEN_UID` and the configured native token.
- Start the wallet by adding the native token received from the fullnode
Requires https://github.com/HathorNetwork/hathor-wallet-lib/pull/689 to be merged and released.
> feat: native token config

- src/utils/helpers.js
- We should update the tx mining service URL in the lib config when the wallet is started
> fix: save tx mining server on the lib config when wallet is started

- locale/texts.pot
- src/components/OutputData.js
- src/components/SendDataOutputOne.js
- src/screens/SendTokens.js
- It should add "Add data output" button on Token Transaction screen
- It should add a new tile in the list of tokens representing a data output when "Add data output" is clicked 
- It should have a "Remove" button on each data output tile
- It should remove the data output tile itself when "Remove" is clicked
- It should add each data output to transaction's outputs as a `data` output, converting any input value to a string
The following transaction is an example of a token transaction sent with data output.
https://explorer.testnet.hathor.network/transaction/00002a0dabb26966a74f67522db275d7174dfdfc3c151c4d1d788f4daa0b16c9
> feat: add data output to token transaction

- SHORT_QA.md
- The short QA must validate the checksum of the binaries
> docs: Checksum validation on SHORT_QA

- package-lock.json
- package.json
- src/components/TxData.js
- src/screens/nano/NanoContractDetail.js
- Nano contract detail screen must use the new custom types to format attributes and show information to the user in a better way
- Transaction detail screen must use the new custom types to format arguments of a nano contract tx and show information to the user in a better way
> feat: improve UI/UX for nano state detail and tx data with new custom types

- src/components/BackButton.js
- src/components/ResetNavigationLink.js
- src/screens/nano/NanoContractDetail.js
The back button of the Nano Contract Detail screen was working fine when we clicked a nano contract from the registered link. However, after creating a new nano contract, or after executing a nano contract method, the back button was navigating to the form screen, instead of the Registered list screen.
I created a new component that has a link to navigate to any screen.
- Add `ResetNavigationLink` component and use it in the nano contract detail screen.
- BackButton component should use this new navigation link component.
https://github.com/user-attachments/assets/1e6ab7eb-54d5-4d1f-aeeb-8838b242eaa4
> feat: create a reset navigation link component to be used by the nano contract detail screen

- src/screens/Server.js
- src/screens/nano/NanoContractDetail.js
- src/screens/nano/NanoContractSelectBlueprint.js
- src/utils/version.js
- Use `getNetworkFromFullNodeNetwork` from lib helpers utils to get wallet network from full node network.
- Use constant for nano contract initialize method string from the lib instead of hardcoded string.
> refactor: use lib methods to avoid duplicate code

- src/components/GlobalModal.js
- src/components/nano/ModalSelectAddressToSignTx.js
- src/screens/nano/NanoContractExecuteMethod.js
- Add link below the input for the Address to Sign tx to open a modal that helps user select an address from the loaded wallet.
https://github.com/user-attachments/assets/91ab7617-739c-4198-a51a-1ceb9aa6f2ba
> feat: add modal to help user to select an address to sign the nano initialize tx

- src/screens/CreateNFT.js
This PR https://github.com/HathorNetwork/hathor-wallet-lib/pull/596 changes the method to declare an NFT creation on `prepareCreateNewToken` method, but the wallet desktop wasn't updated.
- NFT creation transaction must have a data output
It closes https://github.com/HathorNetwork/internal-issues/issues/397
> fix: nft creation without data ouput

- release.sh
- shasum-sign.sh
1. Fails fast release.sh when team id is missing.
2. Show latest git commit in log.
3. Add the `shasum_sign.sh` script which generates the `SHA256SUMS` and `SHA256SUMS.asc` files.
> chore(release): Improve release scripts

- src/sagas/wallet.js
- src/utils/wallet.js
- Correctly load custom token balances when starting the wallet
This bug was introduced in this refactor: https://github.com/HathorNetwork/hathor-wallet/pull/587
> fix: allTokens variable is a list, not an object

- src/index.module.scss
- src/screens/nano-contract/NanoContractDetail.js
Depending on the length of the method names, the UI is still not good with 5 columns. I changed to 3 columns only, which fits well the blueprints we have nowadays. If the method names are too big, it will still break but this is unlikely because they are also code method names, which shouldn't be too big, so I think it's safe to go with this solution for now.
- Use only 3 columns to list the available methods of a nano contract.
Old UI:
New UI:
> fix: use 3 columns in the methods list

- src/actions/index.js
- src/constants.js
- src/reducers/index.js
- src/sagas/nanoContract.js
- src/screens/nano-contract/NanoContractDetail.js
- Verify if transaction is confirmed before getting nc state and history. If it's not confirmed, add a loading and keep polling the data.
The currently screen when we get the state before the tx is confirmed
New screen waiting confirmation
> feat: verify is tx is confirmed before getting nc state

- src/components/InputNumber.js
- src/components/OutputsWrapper.js
- src/components/SendTokensOne.js
- src/components/atomic-swap/ModalAtomicReceive.js
- src/components/atomic-swap/ModalAtomicSend.js
- src/components/tokens/TokenMelt.js
- src/components/tokens/TokenMint.js
- src/screens/CreateNFT.js
- src/screens/CreateToken.js
- src/screens/nano-contract/NanoContractExecuteMethod.js
- src/utils/tokens.js
- src/utils/wallet.js
In our network, the amount used by output values is always an integer number, that is, it cannot have a fractional part. However, we do have decimal places for _cosmetic only_ reasons: we show 2 decimal places for tokens and 0 decimal places for NFTs.
This means internally amount values should always be handled (stored, sent, processed) as integer values, and we should only consider decimal places when interfacing with the user, that is, displaying values or receiving input. This is straightforward in Python by using the `int` type. In JS, the `Number` type is used, which is a `double`.
This resulted in a bit of a mess in our wallet code. Currently, we have different functions/react components storing and expecting amounts in different formats. Sometimes, strings are used and they have to …
> refactor: improve amount handling

- src/components/ModalAddManyTokens.js
- src/components/ModalAddToken.js
- src/components/atomic-swap/ModalAtomicReceive.js
- src/components/atomic-swap/ModalAtomicSend.js
- src/utils/wallet.js
Some constants were missing to be updated from `number` to `bigint`.
- Change constants from `0` to `0n`.
> fix: missing bigint constants

- QA_LARGE_VALUES.md
- README.md
- package.json
- qa/large-values-network/checks.py
- qa/large-values-network/docker-compose.yml
- qa/large-values-network/privnet.yml
Since the wallet-desktop currently doesn't have automated tests, this PR adds a new QA to make specific checks when handling large output values (`BigInt`). It introduces a docker compose that runs a complete custom network (full node, tx-mining-service, and CPU miner). The new QA described in `QA_LARGE_VALUES.md` should be incorporated as part of the QA process for this project.
- Add new `QA_LARGE_VALUES.md`.
- Change debug command in README to use equivalent npm script.
- Add new QA npm scripts config.
- Add new QA python script, docker compose, and custom network config files.
> docs(qa): add large values QA

- src/components/TxData.js
- src/screens/nano-contract/NanoContractDetail.js
Transaction detail screen was crashing on nano contract transactions because the `prettyValue` method from wallet-lib expects a BigInt:
`React Router caught the following error during render Error: value 500 should be a bigint`
- The transaction detail screen should work for nano contract transactions
> fix: bigint on TxData and NanoContractDetails

- package-lock.json
- package.json
- Bumps to public release version `0.31.0`
> chore: bump to 0.31.0

- src/screens/nano-contract/NanoContractDetail.js
The nano contract detail screen is currently throwing an error if an amount argument exists. It uses the `prettyValue` method that expects a `bigint` but it's currently returning a `number`.
There's a [full node PR](https://github.com/HathorNetwork/nano-hathor-core/pull/167) in review process that will add support for bigint in the Amount nano arguments, so this handling code won't be needed as soon as it's merged and we also add this support in the wallet-lib.
- Handle amount nano argument as big int or number.
> fix: nano amount is not coming as big int from the lib

- src/components/InputNumber.js
- src/sagas/nanoContract.js
- src/screens/nano-contract/NanoContractDetail.js
- src/screens/nano-contract/NanoContractExecuteMethod.js
- src/screens/nano-contract/NanoContractList.js
- We should hide the execute and register nano contract buttons for now (they need to be updated to the new wallet-lib methods, for now they'll work only with Reown/WalletConnect)
- Fixed wrong method call in `nanoContracts` saga preventing the nano contract details screen to be shown
> refactor: hide register execute nc

- src/sagas/wallet.js
On wallet start we were creating an event channel that was being closed only when the saga was cancelled, so the channel would stay opened even after the wallet was stopped.
- Close event channel on wallet stopped.
> fix: close event channel on wallet stopped

- src/sagas/wallet.js
After wallet reset, the wallet object was still receiving ws messages, and the handling would throw an error because the storage was being cleaned.
- Stop wallet on wallet reset instead of just cleaning the storage
> fix: stop wallet on wallet reset

- locale/texts.pot
- src/actions/index.js
- src/components/Reown/FeedbackModal.js
- src/components/Reown/NanoContractActions.js
- src/components/Reown/NanoContractFeedbackModal.js
- src/components/Reown/modals/BaseNanoContractModal.js
- src/reducers/index.js
- src/sagas/reown.js
- src/sagas/tokens.js
- We shouldn't register action tokens as soon as a Reown request arrives.
- We should download data and store in a separate redux state to be used by the component to show the symbol
- We should ask the user to register the unregistered tokens after the tx is sent successfully.
In the video we have the tokens not registered in the first request. The actions show the symbol correctly and we ask if the user wants to register them. In the second request we don't ask anything because the tokens are already registered, and the symbol appears in the actions list as well.
https://github.com/user-attachments/assets/7700ad34-d116-441d-bd81-8362b014de43
> feat: handle unregistered tokens actions properly and ask user to register them
